# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 23:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('folhaponto', '0002_auto_20171113_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('sexo', models.CharField(max_length=1)),
                ('idade', models.IntegerField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEHoraDeInicio', models.DateTimeField(blank=True, null=True)),
                ('dataEHoraDeFim', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.BooleanField(default=True, verbose_name=b'HorarioTipo')),
                ('ip', models.CharField(max_length=128)),
                ('nomechefe', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='participante',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='evento',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Inscricao',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.AddField(
            model_name='frequencia',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_dados', to='folhaponto.Funcionario'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horario_funcionario', to='folhaponto.Horario'),
        ),
    ]
