# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folhaponto', '0003_auto_20171113_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='status',
            field=models.BooleanField(default=True, verbose_name=b'CONSISTENTE'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='tipo',
            field=models.BooleanField(default=True, verbose_name=b'Estagiario'),
        ),
    ]
