# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folhaponto', '0004_auto_20171113_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='status',
        ),
    ]
