# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folhaponto', '0005_remove_frequencia_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='status',
            field=models.BooleanField(default=True, verbose_name=b'CONSISTENTE'),
        ),
    ]
